config/routes.rb
Rails.application.routes.draw do
  

  resources :friendships  
  resources :images
  root 'chatroom#index' 	 
  post 'message', to: 'messages#create'
   resources :userinfos 
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post "login", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  delete 'login', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	before_action :require_user

  def index
  	@message = Message.new
    @messages = Message.custom_display
  end
	def create
	  	 
	  end

end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatroom/_chatroom.html.erb
<div class= "ui two column grid">  
      <div class="twelve wide column">
         <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
               <div class="ui feed" id="message-container">
                   <%= render @messages %>
                </div>
            
            </div>

            <div class="extra content">
              
           <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
                        <div class="field">
                           <div class="ui fluid icon input">
                            <%= f.text_field :body, placeholder: "Enter a message..." %>
                             <%= f.button '<i class="borderd inverted  teal edit icon"></i>' .html_safe %>
                           </div>
                       </div>
                <%end%>
             </div>
           </div>

      </div>

   <div class="four wide column">
      <div class="ui fluid raised card chatbox">
          <div class="content">
            <div class="ui inverted vertical menu">
               <a class="active item">
               Home
               </a>
              <%= link_to "Account", user_path(current_user), class: "item"%>
              <%= link_to "Users", users_path,  class: "item"%> 
            </div>
         </div>
      </div>
    </div>

</div>

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  Say something!
  <div class="ui section divider"></div>

   <i class="circular teal comments outline icon"></i>
   <div class="ui section divider"></div>
    Ping me!
</h4>

<%= render 'chatroom' %>