config/routes.rb
Rails.application.routes.draw do
  

  resources :friendships  
  resources :images
  root 'chatroom#index' 	 
  post 'message', to: 'messages#create'
   resources :userinfos 
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post "login", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  delete 'login', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/user.rb
class User < ApplicationRecord
has_many :userinfos, dependent: :destroy

has_many :messages, dependent: :destroy
has_many :images, dependent: :destroy

 has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships  
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"  
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


before_save {self.email = email.downcase}
     
    validates :username, presence: true, 
                    uniqueness: {case_sensitive: false}, 
                    length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	 validates :username, presence: true, 
                    uniqueness: {case_sensitive: false}, 
                    length: {minimum: 3, maximum: 25}
 	has_secure_password


def count_friends
	friends.all.count
  end

 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

   def show
    @userinfos = @user.userinfos
  end

  def index
    @users = User.all
   end
  

  def new
    @user = User.new
  end


	def create
   	 @user = User.new(user_params)
	    if @user.save
 	      session[:user_id] = @user.id
	      flash[:notice] = "Welcome to PingMe #{@user.username}, you have successfully signed up"
	      redirect_to @user
	    else
	      render 'new'
	    end
	end


	def edit
	end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


	def destroy
	    @user.destroy
	    session[:user_id] = nil if @user == current_user
	    flash[:notice] = "Account and all associated articles successfully deleted"
	    redirect_to root_path
	  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end


end

app/views/users/_signup.html.erb
<div class="ui placeholder segment">
  <%=render "layouts/flashmessages", obj: @user%>
  <div class="ui column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
      <%= form_with(model: @user, local: true) do |f| %>
           
        <div class="field">
         <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Create a Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :email, "Email" %>
          <div class="ui left icon input">
            <%= f.email_field :email, placeholder: "Enter your email address" %>
            <i class="lock icon"></i>
          </div>
        </div>
         <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Choose a Password" %>
            <i class="lock icon"></i>
          </div>

        </div>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class:  "ui inverted blue button") %>
          <% if logged_in? %>          
        <%= link_to "Delete Account", user_path(current_user), 
          class: "ui inverted red button", method: :delete, data: { confirm: "Are you sure?" } %> 
          <%end%>
          <div class="field">
            <div class="ui checkbox">
               <input type="checkbox" tabindex="0" class="hidden">
               <label>I agree to the Terms and Conditions</label>
                <div class="middle aligned column">
                   <%= link_to "Cancel", root_path,  class: "ui teal button" %>
              </div>

      <% end %>

      </div>
    </div>

    </div>
  </div>
</div>

app/views/users/_userProfile.html.erb
<div class="ui center aligned medium icon header">
   <div class="ui link cards">
      <div class="card">
           <%= image_tag "avatar3.png", class: "ui small image" %>
         <div class="content">
            <% @users.each do |user| %>
            <div class="content">
            	<div class="header">
               <%= user.username %>
           		</div>
               <div class="meta">
                  <a>Friends</a>
               </div>
               <div class="description">
                   <%= user.username %> is an interior designer living in New York.
               </div>
            </div>
            <div class="extra content">
               <span class="right floated">
               Joined <%= time_ago_in_words(user.created_at)%> ago,
               </span>
               <span>
               <i class="user icon"></i>
               75 Friends
               </span>
            </div>
         </div>
         <%end%>
      </div>
      

   </div>
</div>

app/views/users/_userlist.html.erb
<div class="ui link cards">
  <html>
  <body>
    <header class="flex">
      <button>Shuffle User Card Deck</button>
    </header>
    <section class="flex">
      <img src="">
    </section>
    <script src="assets/javascripts/application.js"></script>
  </body>
</html>
       <% @users.each do |user| %>
  <%if current_user != user %>

  <div class="card ">
    <div class="image">
              <%= @image = current_user %>
    </div>
    <div class="content">
      <% if logged_in? %>
      <%= link_to user.username,user, class: "ui inverted header "%>
      <%else%>
      <%= user.username %>
      <%end%>
       <div class="meta">  
        <p>  
          <button class="ui basic button">
         <i class="icon user"></i>

          <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>  </button>
        </p> 
  
      </div>  
         <div class="description">
          <%= user.username %> is is an interior designer living in New York.
        </div>
    </div>
    <div class="extra content">
      <span class="right floated">
        Joined <%= time_ago_in_words(user.created_at)%> ago,
      </span>
      <span>
        <i class="user icon"></i>
         <%= user.count_friends%>
      </span>
    </div>    
  </div>
    <%end%>
          <%end%> 
</div>
 

app/views/users/edit.html.erb
<h4 class= "ui center aligned medium icon header "> Edit Your Account </h4>
    <%= render 'signup' %>

app/views/users/index.html.erb
<h4 class="ui center aligned medium icon header">
   List of Users
   <div class="ui section divider"></div>
   <i class="circular teal comments outline icon"></i>
   <div class="ui section divider"></div>
 
</h4>
  <%= render 'userlist' %>

app/views/users/new.html.erb
<h4 class="ui center aligned medium icon header ">
      Welcome To PingMe - An Instant Messaging Platform
      <div class="ui section divider"></div>
   <i class="circular teal comments outline icon  "></i>
   <div class="ui section divider"></div>
   Signup to start Pinging!
</h4>
<%= render 'signup' %>

app/views/users/show.html.erb
<h1 class= "ui center aligned medium icon header "> <%= @user.username %>'s' Profile </h1>
<%if logged_in? && @user == current_user%>
<div class= "ui center aligned medium icon header">
   <%= link_to "Edit your Account", edit_user_path(@user), class: "ui teal submit button" %>
   <%= link_to "Edit your Profile", edit_userinfo_path(current_user), class: "ui inverted green button"%>
</div>
<%end%>
<table class="ui center very basic collapsing celled table">
   <thead>
      <tr>
         <th>Friends</th>
         <th>Actions</th>
         <th>Users who have added you</th>
         <th>View profile</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>
            <h4 class="ui image header">
               <img src="/images/avatar2/small/lena.png" class="ui mini rounded image">
               <div class="content">
                  <% for friendship in @user.friendships %>
                  <%= friendship.friend.username %>  
                  <% end %>       
                  <div class="sub header">Human Resources
                  </div>
               </div>
            </h4>
         </td>
         <td>
            <%= link_to "remove", friendship, method: :delete, data: {confirm: "Are you sure?"},
               class: 'negative ui button'%>
         </td>
         <td>
            <% for user in @user.inverse_friends %>  
            <li><%= user.username %></li>
            <% end %>  
         </td>
         <td>
   <%= link_to user.username,user, class: "ui header "%>         </td>
      </tr>
   </tbody>
</table>
<%= render 'userinfos/usersinfo' %>