config/routes.rb
Rails.application.routes.draw do
  

  resources :friendships  
  resources :images
  root 'chatroom#index' 	 
  post 'message', to: 'messages#create'
   resources :userinfos 
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post "login", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  delete 'login', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/userinfo.rb
class Userinfo < ApplicationRecord
      belongs_to :user
        
        validates :title, presence: true, length: {minimum: 6, maximum: 100}
        validates :description, presence: true, length: {minimum: 10, maximum: 300}
        validates  :user_id, :eduction, :from, :contactinfo, :company, :passions, :Jobtitle, presence: true
 end

app/controllers/userinfos_controller.rb
class UserinfosController < ApplicationController
  before_action :set_userinfo, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
  end

  def index
   @userinfos = Userinfo.all
   end

 def new
    @usersinfo = Userinfo.new
  end

  def create
    @userinfo = Userinfo.new(userinfo_params)
    @userinfo.user = current_user
    if @userinfo.save
      flash[:notice] = "Info was created successfully."
      redirect_to userinfos_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @userinfo.update(userinfo_params)
      flash[:notice] = "Info was updated successfully."
      redirect_to userinfos_path
    else
      render 'edit'
    end
  end

  def destroy
    @userinfo.destroy
    redirect_to userinfos_path
  end

  private

  def set_userinfo
     @userinfo = Userinfo.new(id: params[:id])
  end

  def userinfo_params
    params.require(:userinfo).permit(:title, :description, :user_id, :eduction, :from, :contactinfo, :company, :passions, :Jobtitle )
  end 
  def require_same_user
    if current_user != @userinfo.user  
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to  userinfos_path
    end
  end

end

app/views/userinfos/_editusersinfo.html.erb
<div class="ui placeholder segment">
  <%=render "layouts/flashmessages", obj: @userinfo%>
  <div class="ui column very relaxed stackable grid">
    <div class="column">
      <div class="ui form"> 
 <%= form_with(model: @userinfo, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
       <div class="field">
          <div class="ui left icon input">
            <%= f.file_field :picture  %>
           </div>
        </div>

        <div class="field">
          <%= f.label :title, "Title" %>
          <div class="ui left icon input">
            <%= f.text_field :title, placeholder: "Enter your Title" %>
            <i class="lock icon"></i>
          </div>
        </div>
       <div class="field">
          <%= f.label :description, "Discribe yourself" %>
          <div class="ui left icon input">
            <%= f.text_field :description, placeholder: "Discribe yourself" %>
            <i class="lock icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :contactinfo, "Contact" %>
          <div class="ui left icon input">
            <%= f.text_field :contactinfo, placeholder: "Enter your contact information" %>
            <i class="lock icon"></i>
          </div>


            <div class="field">
          <%= f.label :from, "Where are you from?" %>
          <div class="ui left icon input">
            <%= f.text_field :title, placeholder: "Where are you from" %>
            <i class="lock icon"></i>
          </div>
        </div>

        </div>
        <div class="field">
          <%= f.label :Jobtitle, "Job Title" %>
          <div class="ui left icon input">
            <%= f.text_field :Jobtitle, placeholder: "Enter your Job Title" %>
            <i class="lock icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :company, "Who do you work for?" %>
          <div class="ui left icon input">
            <%= f.text_field :company, placeholder: "Enter Company" %>
            <i class="lock icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :eduction, "List your Eduction" %>
          <div class="ui left icon input">
            <%= f.text_field :eduction, placeholder: "Enter your Eduction" %>
            <i class="lock icon"></i>
          </div>
        </div>

          <div class="field">
          <%= f.label :passions, "What are your Passions?" %>
          <div class="ui left icon input">
            <%= f.text_field :passions, placeholder: "Enter your passions" %>
            <i class="lock icon"></i>
          </div>
        </div>
          <div class="form-group row justify-content-center">
          <%= link_to "update profile", users_path, class: "ui inverted blue button" %>
 
  <%end%>

app/views/userinfos/_usersinfo.html.erb
<div class="ui placeholder segment">
   <%=render "layouts/flashmessages", obj: @userinfo%>
   <div class="ui column very relaxed stackable grid">
      <div class="column">
         <div class="ui form">
            <% @userinfos.each do |userinfo| %>
            <div class="card-body">
               <h5 class="card-title"> 
                  <%= link_to userinfos.title, userinfos_path(userinfo), class: "text-success" %>
               </h5>
               <p class="card-text"><%= truncate(userinfo.description, length: 100) %></p>
               <%= link_to userinfos.user_id, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.eduction, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.from, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.contactinfo, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.company, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.passions, userinfos_path(userinfo), class: "text-success" %></h5>
               <%= link_to userinfos.Jobtitle, userinfos_path(userinfo), class: "text-success" %></h5>
            </div>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/userinfos/edit.html.erb
<h1 class= "text-center mt-4"> Create Your Profile </h1>
  <%= render 'editusersinfo' %>
 <%= link_to "Delete Profile", userinfo_path(current_user), 
          class: "ui inverted red button", method: :delete, data: { confirm: "Are you sure?" } %> 

app/views/userinfos/new.html.erb
<h1 class= "text-center mt-4"> Add your inforamtion </h1>
 <%= render 'editusersinfo' %>