config/routes.rb
Rails.application.routes.draw do
  

  resources :friendships  
  resources :images
  root 'chatroom#index' 	 
  post 'message', to: 'messages#create'
   resources :userinfos 
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post "login", to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  delete 'login', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/views/layouts/_flashmessages.html.erb
<% flash.each do |message_type, message_content| %>
	<div class="ui <%= message_type %> message transition">
	  <i class="close icon"></i>
	  <div class="header">
	    <%= message_content %>
	  </div>
	 </div>
<%end%>

app/views/layouts/_footer.html.erb
<div class="ui segment">
  <div class="ui inverted vertical footer segment">


        <div class="ui center aligned container">
          <div class="ui center aligned stackable inverted divided equal height stackable grid ">
            <div class="three wide column">
              <h4 class="ui inverted header">About</h4>
              <div class="ui inverted link list">
                <a class="item" href="#root">Sitemap</a>
                <a class="item" href="#root">Contact Us</a>
              </div>
            </div>
            <div class="three wide column">
              <h4 class="ui inverted header">Support</h4>
              <div class="ui inverted link list">
                <a class="item" href="#root">FAQs</a>
              </div>
            </div>
            <div class="seven wide column">
              <h4 class="ui inverted header">Copyright </h4>
              	 <small>&copy;
               <%= link_to "Stephen's Github", "https://github.com/stephenh0191", class: "text-white" %> 
        </small>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
</div>

app/views/layouts/_navigation.html.erb
 
<%= link_to "Home", login_path, class: "item"  %>
 <% if logged_in? %>
<%= link_to "Users", users_path, class: "item"%>
<%= link_to "Messages",root_path, class: "item"%>
<%end%>

<div class="right menu">
   <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
    
      <div class="menu">
        <% if logged_in? %>
      <%= link_to "View your Profile", user_path(current_user), class: "ui inverted primary button"%>
      <%= link_to "Edit your Account", edit_user_path(current_user), class: "ui inverted green button"%>
      <%= link_to "Edit your Profile", edit_userinfo_path(current_user), class: "ui inverted green button"%>

           <%= link_to "Log out", logout_path , method: :delete, class: "ui  item " %>

        <%else %>
        <%= link_to "Log in", login_path,  class: "ui inverted secondary button"%> 
        <%end%>
       </div>
   </div>

    <% if !logged_in? %>
   <div class="item">
     <%= link_to "Log in", login_path,  class: "ui primary button"%> 
   </div>
   <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>PingMe</title>

      <%= favicon_link_tag %>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
      <div class="ui small inverted menu">
         <div class="ui container">
            <%= render "layouts/navigation"%>
         </div>
      </div>

      <div class="ui container">
         <%= render 'layouts/flashmessages'%>
         <%= yield %>
      </div>
      
   </body>
    
</html>

 <%= render 'layouts/footer'%>